### ISSUE TITLE
support YAML as the alternative gating template format

### ISSUE THREAD

**Issue by mikejiang** [RGLab/flowIncubator#27]
`yaml` may be helpful to describe the `gating tree` due to its support of hierarchical data structure 
```YAML
name: root
boundary:
  name: boundary
  dims: FSC-A,SSC-A
  gating_args: max = c(250000, 250000)
  gating_method: boundary
  pop: boundary
  nonDebris:
    name: nonDebris
    dims: FSC-A
    gating_args: gate_range = c(50000, 100000), adjust = 1.5
    gating_method: mindensity
    pop: nonDebris+
    lymph:
      name: lymph
      dims: FSC-A,SSC-A
      gating_args: K = 2, quantile = 0.95, target = c(100000, 50000)
      gating_method: flowClust
      pop: lymph
      preprocessing_args: K = 2
      preprocessing_method: prior_flowClust
      Live:
        name: Live
        dims: Live
        gating_args: tol = 0.05
        gating_method: tailgate
        pop: Live-
        preprocessing_method: standardize_flowset
```

By leveraging `data.tree` and `yaml` package, it should be straightforward to interchange both versions of `template`:  `csv` and `yaml`.
